name: push

on:
  push:
    branches: [main]

jobs:
  test-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - name: Test 📱
        run: npm test
      - uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
